<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net40;net452;net462;net472;net48;netcoreapp3.1;net6.0-windows;net8.0-windows;net9.0-windows;</TargetFrameworks>
		<UseWPF>True</UseWPF>
		<AutoGenerateBindingRedirects Condition="$(TargetFramework.StartsWith('net4'))">true</AutoGenerateBindingRedirects>
		<AssemblyName>WPFLocalizeExtension</AssemblyName>
		<Version>$(GitVersion_NuGetVersion)</Version>
		<AssemblyTitle>WPFLocalizeExtension</AssemblyTitle>
		<PackageId>WPFLocalizeExtensionEzzFork</PackageId>
		<Authors>Bernhard Millauer,Uwe Mayer, Konrad Mattheis</Authors>
		<PackageLicenseExpression>MS-PL</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/ezhassen/WPFLocalizationExtension/</PackageProjectUrl>
		<Copyright>Bernhard Millauer, Uwe Mayer, Konrad Mattheis</Copyright>
		<Description>LocalizationExtension is a really easy way to localize any type of DependencyProperties or native Properties on DependencyObjects (This is a fork to support .net core 3.1 to net9.0)</Description>
		<Company>ezhassen</Company>
		<Product>WPF Localization Extension</Product>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<PackageReleaseNotes></PackageReleaseNotes>
		<NeutralLanguage>en-US</NeutralLanguage>
		<PackageTags>wpf localization extension globalization resx csv resource language</PackageTags>
		<RepositoryUrl>https://github.com/ezhassen/WPFLocalizationExtension</RepositoryUrl>
		<PackageReleaseNotes></PackageReleaseNotes>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
		<SignAssembly>true</SignAssembly>
		<DelaySign>false</DelaySign>
		<PublicSign>true</PublicSign>
		<AssemblyOriginatorKeyFile>public.snk</AssemblyOriginatorKeyFile>
		<!--Workaround for Error	MSB4216	Could not run the "GenerateResource" -->
		<GenerateResourceMSBuildArchitecture>CurrentArchitecture</GenerateResourceMSBuildArchitecture>

		<RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>

		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<GenerateDocumentationFile>false</GenerateDocumentationFile>

		<UnSignedFlag></UnSignedFlag>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\LICENSE" Pack="true" PackagePath="" />
		<None Remove="packages.lock.json" />
		<None Remove="public.snk" />
	</ItemGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<PropertyGroup Condition="Exists('$(SolutionDir)\src\fullkey.snk')">
		<PublicSign>false</PublicSign>
		<AssemblyOriginatorKeyFile>fullkey.snk</AssemblyOriginatorKeyFile>
	</PropertyGroup>

	<PropertyGroup Condition="'$(UnSigned)' == 'true'">
		<SignAssembly>false</SignAssembly>
		<PublicSign>false</PublicSign>
		<AssemblyOriginatorKeyFile></AssemblyOriginatorKeyFile>
		<PackageId>$(AssemblyName).UnSigned</PackageId>
		<UnSignedFlag>.UnSigned</UnSignedFlag>
		<!--we can handle only one packages.lock.json so for now for unsigned just disable the usages-->
		<RestorePackagesWithLockFile>false</RestorePackagesWithLockFile>
	</PropertyGroup>

	<!--References for .Net Framwork 4 and 35-->
	<ItemGroup Condition="$(TargetFramework.StartsWith('net4'))">
		<Reference Include="System.Management" />
	</ItemGroup>

	<!--References for .Net Core 3.x + net6+-->
	<ItemGroup Condition="!$(TargetFramework.StartsWith('net4'))">
		<PackageReference Include="System.Management" Version="9.0.6" />
		<PackageReference Include="System.Drawing.Common" Version="9.0.6" />
	</ItemGroup>

	<!--PackageReference for all framworks-->
	<ItemGroup>
		<PackageReference Include="XAMLMarkupExtensionsEzzFork" Version="2.1.4" />
		<!--GitVersion.MsBuild version 6.0.2 there issues whith some projects (To show in updates again just remove [])-->
		<PackageReference Include="GitVersion.MsBuild" Version="[5.12.0]" PrivateAssets="All" />
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
	</ItemGroup>

	<Target Name="PublishToNugetWithAPIKey" AfterTargets="GenerateNuspec">
		<ReadLinesFromFile Condition="Exists('$(SolutionDir)\..\..\ezznugetapikey.txt')" File="$(SolutionDir)\..\..\ezznugetapikey.txt">
			<Output TaskParameter="Lines" PropertyName="NugetAPIKey" />
		</ReadLinesFromFile>
		
		<Exec Condition="('$(NugetAPIKey)' != '')" WorkingDirectory="$(BaseDir)" Command="dotnet nuget push $(PackageOutputAbsolutePath)$(PackageId).$(PackageVersion).nupkg -k $(NugetAPIKey) -s https://api.nuget.org/v3/index.json" />
	</Target>

	<Target Name="FixOnGitVersionTaskError" BeforeTargets="GetAssemblyVersion">
		<CreateProperty Value="0.0.1-notgitversion" Condition="'$(GitVersion_NuGetVersion)' == ''">
			<Output TaskParameter="Value" PropertyName="Version" />
		</CreateProperty>
	</Target>
</Project>
